apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepull-demo
  namespace: demo-broken-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepull-demo
  template:
    metadata:
      labels:
        app: imagepull-demo
    spec:
      containers:
        - name: app
          image: ghcr.io/example/not-existing-image:missing-tag
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
